name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Remove Python setup

    - name: Install Docker CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io

    - name: Build Docker Image
      run: |
        docker build -t myapp .

    - name: Push Docker Image
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker tag myapp ${{ secrets.DOCKER_USERNAME }}/myapp:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/myapp:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Remove Python setup

    - name: Install Docker CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io

    - name: Pull Docker Image
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker pull ${{ secrets.DOCKER_USERNAME }}/myapp:latest

    - name: Run Docker Container
      run: |
        docker run -d -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/myapp:latest
